version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo rm -rf /var/lib/apt/lists/*
      - sudo apt-get update
      - sudo apt install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      
artifacts:
  files:
    - /var/www/html/index.html
