version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo dnf update -y
      - sudo apt install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      # Add NGINX configuration commands here if needed
artifacts:
  files:
    - /var/www/html/index.html
